extends TestBase

const ActorScript = preload("res://scripts/ai/ptcgdap/host/godot/PtcgDAPModelActor.gd")
const FIXTURE := "res://tests/ai/ptcgdap/fixtures/platform_actor.ort"


func test_model_hash_domains_preserve_binary_nul_separators() -> String:
	# Independently generated by the Python public tensorizer / SHA256 contract.
	return run_checks([
		assert_eq(ActorScript._uid_feature("CSV5C_059"), -614157626),
		assert_eq(ActorScript._uid_feature("LEN_SVI_001"), -1608346849),
		assert_eq(ActorScript._semantic_key({"type": 0, "number": 3}, "CSV5C_059"), "7A7E2D5882CB0392C6C093EDEC273ACB5404AE24F5D4194BC666BC3AF7033866"),
	])


class ModelHandle extends RefCounted:
	var bytes: PackedByteArray
	func _init(value: PackedByteArray) -> void: bytes = value
	func model_payloads() -> Dictionary:
		return {"ok":true, "policy_mode":"rules_with_model", "actor_ort":bytes}
	func local_deck_snapshot() -> Array: return []


func test_native_scores_are_exact_and_model_changes_the_eligible_selection() -> String:
	if not ClassDB.class_exists("PtcgOrtActor"):
		return "Native model component is missing; this platform cannot claim model support"
	var bytes := FileAccess.get_file_as_bytes(FIXTURE)
	if bytes.is_empty(): return "Synthetic ORT fixture missing"
	var native: Variant = ClassDB.instantiate("PtcgOrtActor")
	var loaded: Dictionary = native.load_actor(bytes)
	if not loaded.get("ok", false): return "Model load failed: %s" % loaded
	var f := PackedInt32Array(); f.resize(24); f[0] = 7
	var fp := PackedInt32Array(); fp.resize(24); fp[0] = 1
	var o := PackedInt32Array(); o.resize(1024 * 16); o[0] = 20; o[16] = 3
	var op := PackedInt32Array(); op.resize(1024 * 16); op[0] = 1; op[16] = 1
	var mask := PackedInt32Array(); mask.resize(1024); mask[0] = 1; mask[1] = 1
	# Warm once: cold kernel initialization is measured separately from normal decisions.
	native.run(f, fp, o, op, mask)
	var output: Dictionary = native.run(f, fp, o, op, mask)
	if not output.get("ok", false): return "Model inference failed: %s" % output
	var handle := ModelHandle.new(bytes)
	var created := ActorScript.create(handle)
	var actor: Variant = created.get("owner")
	var frame := {"sequence":7, "prompt_kind":"number", "public_state":{"turn_number":3, "self":{}, "opponent":{}},
		"select_semantics":{"min_count":1,"max_count":1}, "options":[
			{"index":0, "option_type_raw":0, "option_number":20},
			{"index":1, "option_type_raw":0, "option_number":3}]}
	var decision: Dictionary = actor.decide_development_frame(frame, [1], [0,1])
	var vetoed: Dictionary = actor.decide_development_frame(frame, [1], [1])
	return run_checks([
		assert_eq(output.get("option_scores")[0], 29),
		assert_eq(output.get("option_scores")[1], 12),
		assert_eq(output.get("option_scores")[1023], 0),
		assert_eq(output.get("desired_count"), 1),
		assert_true(loaded.has("warmup_elapsed_us"), "Session activation must finish bounded warmup before decisions"),
		assert_true(decision.get("model_used"), JSON.stringify(decision)),
		assert_eq(decision.get("selected_indexes"), [0]),
		assert_eq(vetoed.get("selected_indexes"), [1]),
		assert_true(vetoed.get("model_used"), JSON.stringify(vetoed)),
		assert_eq(ActorScript.preflight_error(handle), ""),
	])


func test_invalid_model_preflight_is_recoverable_and_cannot_start() -> String:
	var handle := ModelHandle.new(PackedByteArray([1,2,3,4]))
	return assert_false(ActorScript.preflight_error(handle).is_empty())


func test_real_v2_package_keeps_original_bytes_and_reaches_native_preflight() -> String:
	var loader: Variant = load("res://scripts/ai/ptcgdap/packages/AuthorStrategyPackageLoader.gd").new()
	var path := "res://tests/ai/ptcgdap/fixtures/platform_model.ptcgai"
	var bytes := FileAccess.get_file_as_bytes(path)
	var digest := HashingContext.new()
	digest.start(HashingContext.HASH_SHA256)
	digest.update(bytes)
	var inspected: Dictionary = loader.inspect_control_distributed_player_match_bytes(bytes, digest.finish().hex_encode().to_upper())
	if not inspected.get("ok", false): return "V2 fixture inspection failed: %s" % inspected
	var deck: Dictionary = load("res://scripts/ai/ptcgdap/packages/AuthorStrategyDeckGate.gd").build(inspected.payloads)
	if not deck.get("ok", false): return "V2 fixture deck failed: %s" % deck
	var created: Dictionary = load("res://scripts/ai/ptcgdap/packages/AuthorStrategyPackageHandle.gd").create(inspected.metadata, inspected.payloads, deck.local_deck)
	if not created.get("ok", false): return "V2 handle failed"
	var handle: Variant = created.handle
	var gate: Variant = load("res://scripts/ai/ptcgdap/host/godot/AuthorStrategyWindowsExecutionGate.gd")
	return run_checks([
		assert_eq(handle.to_public_dict().get("package_schema_version"), 2),
		assert_false(inspected.metadata.has("package_schema_version"), "Portable view must not change public metadata wire keys"),
		assert_eq(gate.validate_handle_pins(handle.to_public_dict(), gate.CONTROL_DISTRIBUTED_MODE), ""),
		assert_eq(ActorScript.preflight_error(handle), ""),
		assert_eq(FileAccess.get_file_as_bytes(path), bytes),
	])
