#!/usr/bin/env python3
"""Import this macOS source checkout before launching its rules player.

Godot --path alone does not import new assets after a pull. Keep the optional
missing model backend out of this machine's scan and stale extension cache.
The distributed .app does not use this development tool or require Python.
"""
import argparse
from pathlib import Path
import platform
import re
import subprocess
import tempfile

try:
    from .export_macos_release import run_logged
except ImportError:
    from export_macos_release import run_logged

EXTENSION = "res://scripts/ai/ptcgdap/native/ptcgai_ort_actor.gdextension"
IGNORE = Path("scripts/ai/ptcgdap/native/.gdignore")
MARKER = "# Generated by run_macos_game.py: optional macOS model libraries are absent.\n"
LIBRARIES = (
    "bin/ptcgai_ort/libptcgai_ort.macos.template_release.universal.dylib",
    "bin/ptcgai_ort/libonnxruntime.dylib",
)


def configure_optional_runtime(root):
    ignore = root / IGNORE
    available = all((root / path).is_file() for path in LIBRARIES)
    if available:
        if ignore.exists() and ignore.read_text() == MARKER:
            ignore.unlink()
        return
    # Leave user-owned ignore files and other cached extensions intact.
    if not ignore.exists():
        ignore.write_text(MARKER)
    cache = root / ".godot/extension_list.cfg"
    if cache.exists():
        original = cache.read_text()
        filtered = "".join(line for line in original.splitlines(keepends=True)
                           if line.strip() != EXTENSION)
        if filtered != original:
            cache.write_text(filtered)


def prepare_project(root, godot, output):
    configure_optional_runtime(root)
    run_logged([str(godot), "--headless", "--path", str(root), "--import"],
               output / "import.log")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--godot", type=Path,
                        default=Path("/Applications/Godot.app/Contents/MacOS/Godot"))
    parser.add_argument("--import-only", action="store_true")
    args = parser.parse_args()
    if platform.system() != "Darwin":
        parser.error("This launcher configures a machine-local macOS checkout only")
    root = Path(__file__).resolve().parents[2]
    godot = args.godot.resolve()
    version = subprocess.check_output([str(godot), "--version"], text=True).strip()
    if not re.fullmatch(r"4\.6\.\d+\.stable\.official\.[a-f0-9]+", version):
        parser.error(f"Use an official Godot 4.6.x editor; got {version}")
    (root / ".tmp").mkdir(exist_ok=True)
    output = Path(tempfile.mkdtemp(prefix="macos-source-", dir=root / ".tmp"))
    print(f"Importing resources with {version}; logs: {output}", flush=True)
    prepare_project(root, godot, output)
    print("Import complete; source checkout is ready.", flush=True)
    if not args.import_only:
        raise SystemExit(subprocess.call([
            str(godot), "--path", str(root), "--log-file", str(output / "game.log"),
        ]))


if __name__ == "__main__":
    main()
