#!/bin/bash
# Arguments are generated by the local application, never evaluated as shell text.
set -euo pipefail
session="$1"; old_pid="$2"; package="$3"; digest="$4"; bytes="$5"
entry="$6"; target="$7"; token="$8"; version="$9"
parent="$(/usr/bin/dirname "$target")"
stage="$session/stage"
backup="$parent/.ptcg-backup-$token.app"
incoming="$parent/.ptcg-incoming-$token.app"
lock="$parent/.ptcg-update.lock"
replaced=0
locked=0
child_pid=''

failure() {
    trap - ERR
    if [ "$replaced" -eq 1 ]; then
        if [ -n "$child_pid" ] && kill -0 "$child_pid" 2>/dev/null; then kill "$child_pid" 2>/dev/null || true; fi
        # Rename only exact application paths, preserving both failed and prior bundles.
        if [ -e "$target" ]; then /bin/mv "$target" "$parent/.ptcg-failed-$token.app" || true; fi
        /bin/mv "$backup" "$target" || { printf 'restore failed' > "$session/rollback_failed.txt"; exit 1; }
        printf 'restored' > "$session/rolled_back"
        /usr/bin/open -n "$target" --args -- "--ptcg-update-rollback=$token" || true
    fi
    printf 'Installation failed; current version or backup has been retained.' > "$session/failed.txt"
    if [ "$locked" -eq 1 ]; then /bin/rmdir "$lock" 2>/dev/null || true; fi
    exit 1
}
trap failure ERR
[[ "$token" =~ ^[0-9a-f]{32}$ && "$digest" =~ ^[0-9a-f]{64}$ && "$old_pid" =~ ^[0-9]+$ ]]
[[ "$target" = /*.app && "$entry" = *.app && "$entry" != */* && "$entry" != *\\* ]]
[[ "$target" != /Volumes/* && "$target" != */AppTranslocation/* ]]
[[ -d "$target" && ! -L "$target" && ! -L "$parent" && ! -L "$session" && ! -L "$package" ]]
[[ -w "$parent" && ! -e "$backup" && ! -e "$incoming" ]]
/bin/mkdir "$lock"
locked=1
[[ "$(/usr/bin/stat -f%z "$package")" = "$bytes" ]]
[[ "$(/usr/bin/shasum -a 256 "$package" | /usr/bin/cut -d ' ' -f 1)" = "$digest" ]]
/bin/mkdir "$stage"
# Validate every ZIP path and reject links before ditto can touch the filesystem.
/usr/bin/zipinfo -1 "$package" > "$session/entries.txt"
/usr/bin/zipinfo -l "$package" > "$session/attributes.txt"
! /usr/bin/grep -Eq '^[lbcps]' "$session/attributes.txt"
count=0
while IFS= read -r name; do
    [[ "$name" = "$entry/"* && "$name" != *\\* && "$name" != *:* ]]
    trimmed="${name%/}"
    case "/$trimmed/" in *'/../'*|*'/./'*|*'//'*) false;; esac
    count=$((count + 1))
    [[ "$count" -le 20000 ]]
done < "$session/entries.txt"
[[ "$count" -gt 0 ]]
/usr/bin/awk '/^[-d]/ { total += $4; if ($4 > 2147483648) exit 1 } END { if (total > 4294967296) exit 1 }' "$session/attributes.txt"
/usr/bin/ditto -x -k "$package" "$stage"
bundle="$stage/$entry"
[[ -d "$bundle/Contents/MacOS" && ! -L "$bundle" ]]
old_id="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$target/Contents/Info.plist")"
new_id="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$bundle/Contents/Info.plist")"
[[ "$old_id" = "$new_id" ]]
[[ "$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$bundle/Contents/Info.plist")" = "$version" ]]
executable="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleExecutable' "$bundle/Contents/Info.plist")"
[[ "$executable" != */* && "$executable" != *\\* && -x "$bundle/Contents/MacOS/$executable" ]]
# Preserve platform trust: never remove quarantine or disable Gatekeeper.
/usr/bin/codesign --verify --deep --strict "$bundle"
/usr/sbin/spctl --assess --type execute "$bundle"
old_team="$(/usr/bin/codesign -dv --verbose=4 "$target" 2>&1 | /usr/bin/sed -n 's/^TeamIdentifier=//p')"
new_team="$(/usr/bin/codesign -dv --verbose=4 "$bundle" 2>&1 | /usr/bin/sed -n 's/^TeamIdentifier=//p')"
[[ -n "$old_team" && "$old_team" != 'not set' && "$old_team" = "$new_team" ]]
/usr/bin/ditto "$bundle" "$incoming"
printf 'ready' > "$session/prepared"
attempt=0
while kill -0 "$old_pid" 2>/dev/null; do
    /bin/sleep 1
    attempt=$((attempt + 1))
    [[ "$attempt" -lt 120 ]]
done
/bin/mv "$target" "$backup"
replaced=1
/bin/mv "$incoming" "$target"
# Direct child launch gives an exact PID for health-check rollback.
"$target/Contents/MacOS/$executable" -- "--ptcg-update-token=$token" > "$session/launch.log" 2>&1 &
child_pid=$!
attempt=0
while [ ! -f "$session/healthy" ]; do
    kill -0 "$child_pid"
    /bin/sleep 1
    attempt=$((attempt + 1))
    [[ "$attempt" -lt 90 ]]
done
[[ "$(/bin/cat "$session/healthy")" = "$version" ]]
printf '%s' "$version" > "$session/success"
replaced=0
/bin/rmdir "$lock"
